version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.18.1
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4443:4443"
      - "4442:4442"
    
  chrome:
    image: selenium/node-chrome:4.18.1
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    ports:
      - "5901:5900"
    shm_size: 2g
    
  firefox:
    image: selenium/node-firefox:4.18.1
    container_name: firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    ports:
      - "5902:5900"
    shm_size: 2g
  
  test:
    build: .
    container_name: test
    depends_on:
      - selenium-hub
      - chrome
      - firefox
    volumes:
      - ./test-output:/app/test-output
    environment:
      - SELENIUM_GRID_URL=http://selenium-hub:4444/wd/hub
      - SELENIUM_REMOTE=true 